language: python
python:
- '2.7'
script:
- echo pypi deployment
deploy:
  - provider: pypi
    user: longma
    password:
      secure: g8vtwb4mqeFqhmHgFG3lxeAYiTZfCsD80O2c8bqVZ6VVpu0mMbU2Qrjd6PBjVuNB3eSySdrHC1H8esuPHY7cmytd2gurGPxZl1dczXzmDSuPOxy44Ml4OZRA2daDSf9dZ1c1pUGfyef7cvjQRxLlIlQp5Rj9qSn2KKmLmxO2QgFafkLEuw/VCe81oAMFq32qfG9DRcE0dbZGkm7P2iHJZhDwUZQpN6rSBSvrpceJHsnZoIHR0ZvtxNxszFFZkBT0kbPjPxc6YovzgASDN167PY+Xi8TL8LHNoiNi2eKPQZutUMKzIKctnUvotiEEgA8EWAfrNLWfz7fUpT/zO1nLhF64TZkNLtdYQ+Ihx4vbO6bzYweXiYK30azezdQODPq22KMKvuVXJsLPZjtLvXGWyYWU4izvGKkDT4p5RCxtCjInhwM3VAlzmX4UBehgi14nugG9UPY86t9bcvLTa8B5D5MrnWdm0LWC/NbNS/uAQvj58XoHs43eHWNo65zVW/XCEYIjM98k4XVU1bqyxEG558dXm9Y5eFswZ0Ec7imwA/pTGehhXBJQQGD80azhonLFD660btuPyj5ocDjg64ulTyCQuYWc/kr2knodhgIyQ0CvZaNkPvAHO0ypLSgSN37Lebwl0ceVCDOiM+bbJaaUN4/ZVlEQ+MFjj949X12nZY4=
    distributions: sdist bdist_wheel
  - provider: pypi
    user: longma
    password:
      secure: g8vtwb4mqeFqhmHgFG3lxeAYiTZfCsD80O2c8bqVZ6VVpu0mMbU2Qrjd6PBjVuNB3eSySdrHC1H8esuPHY7cmytd2gurGPxZl1dczXzmDSuPOxy44Ml4OZRA2daDSf9dZ1c1pUGfyef7cvjQRxLlIlQp5Rj9qSn2KKmLmxO2QgFafkLEuw/VCe81oAMFq32qfG9DRcE0dbZGkm7P2iHJZhDwUZQpN6rSBSvrpceJHsnZoIHR0ZvtxNxszFFZkBT0kbPjPxc6YovzgASDN167PY+Xi8TL8LHNoiNi2eKPQZutUMKzIKctnUvotiEEgA8EWAfrNLWfz7fUpT/zO1nLhF64TZkNLtdYQ+Ihx4vbO6bzYweXiYK30azezdQODPq22KMKvuVXJsLPZjtLvXGWyYWU4izvGKkDT4p5RCxtCjInhwM3VAlzmX4UBehgi14nugG9UPY86t9bcvLTa8B5D5MrnWdm0LWC/NbNS/uAQvj58XoHs43eHWNo65zVW/XCEYIjM98k4XVU1bqyxEG558dXm9Y5eFswZ0Ec7imwA/pTGehhXBJQQGD80azhonLFD660btuPyj5ocDjg64ulTyCQuYWc/kr2knodhgIyQ0CvZaNkPvAHO0ypLSgSN37Lebwl0ceVCDOiM+bbJaaUN4/ZVlEQ+MFjj949X12nZY4=
    distributions: sdist
    on:
      tags: true
after_deploy:
- echo DONE

